
// Auto-generated by compare_models.py
(function() {
    const NEW_MODELS = {
    "ResNet18 (Standard)": {
        "overall": {
            "accuracy": 0.9568,
            "precision": 0.9100467289718562,
            "recall": 0.9948914431671781,
            "f1": 0.9505796216705444,
            "specificity": 0.9025316455695059,
            "avg_confidence": 0.9552912360456288,
            "confidence_distribution": [
                0,
                29,
                47,
                48,
                106,
                1343
            ],
            "confusion_matrix": {
                "TP": 779,
                "TN": 713,
                "FP": 77,
                "FN": 4
            }
        },
        "cataract": {
            "accuracy": 0.9948914431671781,
            "precision": 0.9100467289718562,
            "recall": 0.9948914431671781,
            "f1": 0.9505796216705444,
            "avg_confidence": 0.9552912360456288
        },
        "normal": {
            "accuracy": 0.9025316455695059,
            "precision": 0.0,
            "recall": 0.9025316455695059,
            "f1": 0.0,
            "avg_confidence": 0.9552912360456288
        }
    },
    "VGG16": {
        "overall": {
            "accuracy": 0.9300699300698709,
            "precision": 0.9108669108667996,
            "recall": 0.9527458492974517,
            "f1": 0.9313358301621435,
            "specificity": 0.9075949367087458,
            "avg_confidence": 0.9672154848619547,
            "confidence_distribution": [
                0,
                16,
                24,
                43,
                81,
                1409
            ],
            "confusion_matrix": {
                "TP": 746,
                "TN": 717,
                "FP": 73,
                "FN": 37
            }
        },
        "cataract": {
            "accuracy": 0.9527458492974517,
            "precision": 0.9108669108667996,
            "recall": 0.9527458492974517,
            "f1": 0.9313358301621435,
            "avg_confidence": 0.9672154848619547
        },
        "normal": {
            "accuracy": 0.9075949367087458,
            "precision": 0.0,
            "recall": 0.9075949367087458,
            "f1": 0.0,
            "avg_confidence": 0.9672154848619547
        }
    },
    "DenseNet121": {
        "overall": {
            "accuracy": 0.961856325492628,
            "precision": 0.9581749049428443,
            "recall": 0.9655172413791869,
            "f1": 0.9618320610185805,
            "specificity": 0.9582278481011445,
            "avg_confidence": 0.9585739775061684,
            "confidence_distribution": [
                0,
                20,
                41,
                51,
                82,
                1379
            ],
            "confusion_matrix": {
                "TP": 756,
                "TN": 757,
                "FP": 33,
                "FN": 27
            }
        },
        "cataract": {
            "accuracy": 0.9655172413791869,
            "precision": 0.9581749049428443,
            "recall": 0.9655172413791869,
            "f1": 0.9618320610185805,
            "avg_confidence": 0.9585739775061684
        },
        "normal": {
            "accuracy": 0.9582278481011445,
            "precision": 0.0,
            "recall": 0.9582278481011445,
            "f1": 0.0,
            "avg_confidence": 0.9585739775061684
        }
    }
};
    
    if (typeof MODEL_DATA !== 'undefined') {
        console.log('Merging new comparison models into MODEL_DATA...');
        Object.assign(MODEL_DATA, NEW_MODELS);
    } else {
        window.MODEL_DATA = NEW_MODELS;
    }
    
    // 同时也生成简单的对比数据供参考
    window.MODEL_COMPARISON_SIMPLE = {
    "models": [
        "ResNet18 (Standard)",
        "VGG16",
        "DenseNet121"
    ],
    "accuracy": [
        0.9485,
        0.9301,
        0.9619
    ],
    "time": [
        199.3,
        537.8,
        287.3
    ],
    "params": [
        11.2,
        134.3,
        7.0
    ]
};
})();
